### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac2111]

### ISSUE THREAD

**Issue by sl-he** [pokt-network/pocket-core#804] opened 2020-04-29 19:12 UTC
**Describe the bug**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac2111]

**To Reproduce**
1. Run _pocket start_
2. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS server
 - Version RC-0.2.4

**Additional context**
#033[39;49;22mpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac2111]
#015
goroutine 1 [running]:
github.com/tendermint/tendermint/store.(*BlockStore).LoadBlockMeta(0x0, 0x592, 0x0)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/store/store.go:96 +0xd1
github.com/tendermint/tendermint/store.(*BlockStore).LoadBlock(0x0, 0x592, 0x12af4e0)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/store/store.go:56 +0x4d
github.com/pokt-network/posmint/types.Context.PrevCtx(0x12a00c0, 0xc0000b0190, 0x12ad060, 0xc0004ea200, 0x0, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
#011/home/user/work/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200302134028-19da81a1d77e/types/context.go:154 +0x50b
github.com/pokt-network/pocket-core/x/pocketcore/keeper.Keeper.DeleteExpiredClaims(0x12adde0, 0xc0001fd560, 0x12a7de0, 0xc0004fc6e0, 0x12b0fe0, 0xc000074380, 0x12bb2e0, 0xc00013cb10, 0xc000038d60, 0x1e, ...)
#011/home/user/source/pocket-core/x/pocketcore/keeper/claim.go:223 +0x221
github.com/pokt-network/pocket-core/x/pocketcore/keeper.BeginBlocker(...)
#011/home/user/source/pocket-core/x/pocketcore/keeper/proof.go:20
github.com/pokt-network/pocket-core/x/pocketcore.AppModule.BeginBlock(0x12adde0, 0xc0001fd560, 0x12a7de0, 0xc0004fc6e0, 0x12b0fe0, 0xc000074380, 0x12bb2e0, 0xc00013cb10, 0xc000038d60, 0x1e, ...)
#011/home/user/source/pocket-core/x/pocketcore/module.go:95 +0x157
github.com/pokt-network/posmint/types/module.(*Manager).BeginBlock(0xc0001f0d20, 0x12bce20, 0xc001116580, 0xc00110f020, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, ...)
#011/home/user/work/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200302134028-19da81a1d77e/types/module/module.go:265 +0x1f3
github.com/pokt-network/pocket-core/app.(*pocketCoreApp).BeginBlocker(...)
#011/home/user/source/pocket-core/app/pocket.go:73
github.com/pokt-network/posmint/baseapp.(*BaseApp).BeginBlock(0xc0000ab8c0, 0xc00110f020, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
#011/home/user/work/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200302134028-19da81a1d77e/baseapp/baseapp.go:695 +0x4ce
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000b10a80, 0xc00110f020, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/abci/client/local_client.go:231 +0xf8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc0001fb430, 0xc00110f020, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/proxy/app_conn.go:69 +0x6b
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x12a09c0, 0xc0000c4100, 0x12a9160, 0xc0001fb430, 0xc00000c5a0, 0x12b06e0, 0xc000fbbc60, 0x6, 0xc000fc5640, 0x17)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:280 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0001181c0, 0xa, 0x0, 0xc000fa7770, 0x6, 0xc000fc5640, 0x17, 0x6a4, 0x272, 0xc000fc5660, ...)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:131 +0x17a
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc001139018, 0xa, 0x0, 0xc000fa7770, 0x6, 0xc000fc5640, 0x17, 0x6a4, 0x272, 0xc000fc5660, ...)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/replay.go:475 +0x233
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc001907018, 0xa, 0x0, 0xc000fa7770, 0x6, 0xc000fc5640, 0x17, 0x6a4, 0x272, 0xc000fc5660, ...)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/replay.go:394 +0xdf3
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001139018, 0x12b1160, 0xc0004f04d0, 0x40, 0xe6fba0)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/replay.go:269 +0x485
github.com/tendermint/tendermint/node.doHandshake(0x12b06e0, 0xc000fbbc60, 0xa, 0x0, 0xc000fa7770, 0x6, 0xc000fc5640, 0x17, 0x6a4, 0x272, ...)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/node/node.go:281 +0x19a
github.com/tendermint/tendermint/node.NewNode(0xc000016640, 0x129bcc0, 0xc0000ccb40, 0xc000060740, 0x1284cc0, 0xc000fbbb40, 0xc0001fa570, 0x113ec68, 0xc0001fa580, 0x12a09c0, ...)
#011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/node/node.go:596 +0x343
github.com/pokt-network/pocket-core/app.NewClient(0xc000016640, 0x12a09c0, 0xc000388b20, 0x0, 0x0, 0x113e2d8, 0x12a09c0, 0xc000388b20, 0x0, 0x0)
#011/home/user/source/pocket-core/app/tendermint.go:39 +0x496
github.com/pokt-network/pocket-core/app.InitTendermint(0x0, 0x0, 0xc000b82000, 0x2ed, 0xfc1024, 0x5, 0xfc101f, 0x5, 0x1, 0xc000b82000)
#011/home/user/source/pocket-core/app/config.go:188 +0x485
github.com/pokt-network/pocket-core/app.InitApp(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000b82000, 0x2ed, 0xfc1024, 0x5, ...)
#011/home/user/source/pocket-core/app/config.go:92 +0x148
github.com/pokt-network/pocket-core/app/cmd/cli.glob..func36(0x1b9fc40, 0x1c257b8, 0x0, 0x0)
#011/home/user/source/pocket-core/app/cmd/cli/root.go:73 +0x18d
github.com/spf13/cobra.(*Command).execute(0x1b9fc40, 0x1c257b8, 0x0, 0x0, 0x1b9fc40, 0x1c257b8)
#011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1b9f9c0, 0x44760a, 0x1bb1ae0, 0xc000000180)
#011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
#011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/pokt-network/pocket-core/app/cmd/cli.Execute()
#011/home/user/source/pocket-core/app/cmd/cli/root.go:42 +0x31
main.main()
#011/home/user/source/pocket-core/app/cmd/pocket_core/main.go:8 +0x20

**Comment by andrewnguyen22** [comment] 2020-04-29 19:18
Thanks for your input, this is a duplicate of #784 as it has to do with the loadBlockMeta bug

**Closed as completed by andrewnguyen22** 2020-04-29 19:18 UTC

**Comment by Shaieb524** [comment] 2022-07-18 22:05
i am just have the same problem only when trying to run my golang app (with fx register hooks) as a docker container that connects to a running db container, and it gives this:

[Fx] INVOKE /path/to/api.registerHooks()
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=some address?]

I anybody can help i would appreciate that 
@andrewnguyen22 @sl-he 

Thanks
