### ISSUE TITLE
[BUG REPORT] Nodes aren't being jailed for double signing

### ISSUE THREAD

**Issue by Andrew-Pohl** [pokt-network/pocket-core#1466] opened 2022-08-11 08:39 UTC
**Describe the bug**
When a node get's slashed for double signing it is not being jailed it only get's slashed.

**Expected behavior**
When a node has been identified as committing multiple signatures for the same block it should be slashed and jailed

**Additional context**
I noticed that this was removed over 2.5years ago in[ this commit](https://github.com/pokt-network/pocket-core/commit/864a2476e011c11b1202438368b918c770ab79d4) due to a "bug in tendermint" not sure what this was but I assume it has been fixed nearly 2.5 years on. 

Need to add the following [here](https://github.com/pokt-network/pocket-core/blob/4e55cecdae4438039d67ae895fd82ba7b7f7e6e2/x/nodes/keeper/slash.go#L176)

```
 // reset the signing info
signInfo.ResetSigningInfo()
// jail the validator to prevent consensus problems
k.JailValidator(ctx, address)
// set the jail time duration
signInfo.JailedUntil = ctx.BlockHeader().Time.Add(doubleSignJailDuration)
```

*doubleSignJailDuration I believe this doesn't currently exist looks like prior too 864a2476e011c11b1202438368b918c770ab79d4 it was tombstoning the node (think this might be a little too drastic)

**Comment by POKT-Discourse** [comment] 2022-08-11 08:47
This issue has been mentioned on **Pocket Network Forum**. There might be relevant details there:

https://forum.pokt.network/t/pup-24-increase-slashfractiondoublesign/3352/2

**Comment by oten91** [comment] 2022-08-11 18:48
Hello @Andrew-Pohl : 

-how are you tracking double signings? Usually those events log something that goes like this `"confirmed double sign from x at height y, age of z"` on the info logs. 

they are not to be mixed / confused by events that log something like this : `E[2022-08-11|14:35:14.119] Error attempting to add vote                 module=consensus err="Existing vote: Vote{443:6B74EC18049C 67599/01/1(Prevote) C5B7B1D091B7 DC7DD0F52656 @ 2022-08-11T18:34:33.505659916Z}; New vote: Vote{443:6B74EC18049C 67599/01/1(Prevote) C5B7B1D091B7 21CEB764D4AC @ 2022-08-11T18:34:35.225864741Z}: non-deterministic signature"`

The above event is called non-deterministic signature by tendermint and conceptually is something different than double signing.

-We removed the jailing because tendermint evidence was not reliable at the time to jail nodes in a fair fashion based on evidence by others ( Someone running a validator and syncing from scratch with an old version was able to get others jailed /multiple slashed ) . Nothing have changed since then as we are still on the same version of tendermint.

We have something in the work that may fix this scenario so we can apply the correct penalty to misbehaving nodes.

**Comment by Andrew-Pohl** [comment] 2022-08-11 19:25
Hey @oten91,

instead of reposting it here is @PoktBlade gist of the commit history for block 67200 https://gist.github.com/PoktBlade/78c34c97a015845ad898fba8588b456a 

in this commit log you can see multiple entries from the same validator one example is "71A699F14234B800BACD88EA53867C810A104860" 

can see all the slashing events for this node https://www.poktscan.com/node/71a699f14234b800bacd88ea53867c810a104860. 

without jailing it becomes a repeat offender. These double signings are causing consensus delays (can see this in the fluctuating block times)

**Comment by oten91** [comment] 2022-08-11 19:49
> Hey @oten91,
> 
> instead of reposting it here is @PoktBlade gist of the commit history for block 67200 https://gist.github.com/PoktBlade/78c34c97a015845ad898fba8588b456a
> 
> in this commit log you can see multiple entries from the same validator one example is "71A699F14234B800BACD88EA53867C810A104860"
> 
> can see all the slashing events for this node https://www.poktscan.com/node/71a699f14234b800bacd88ea53867c810a104860.
> 
> without jailing it becomes a repeat offender. These double signings are causing consensus delays (can see this in the fluctuating block times)

Hey @Andrew-Pohl  is this the correct gist? only see one entry for 71A699F14234B800BACD88EA53867C810A104860 using the search function. Can you confirm or point me to it?

Also wanted to comment that neither double signing (as its usually an offense from the previous block not the current) or non-deterministic signature (seen in the log as validator sending duplicate votes) make the consensus rounds take longer. What usually happens is that a validator or multiple validators miss their turn for proposals or are staked heavily and don't vote in time making others wait for the full timeout.

**Comment by Andrew-Pohl** [comment] 2022-08-11 20:58
@oten91 Apologies it's this one https://gist.github.com/PoktBlade/2ffb7131a317f26a27fb05718cd69bd0 

Can see the tendermint/DuplicateVoteEvidence for 

F74DB131709FD55AEA8EC56D22914006802883BB and 71A699F14234B800BACD88EA53867C810A104860

Thanks for clarifying r.e. the delay. Either way this still needs addressing as without jailing incorrectly configured nodes who are consistently double signing increase the risk of forking right?

**Comment by oten91** [comment] 2022-08-12 19:21
> @oten91 Apologies it's this one https://gist.github.com/PoktBlade/2ffb7131a317f26a27fb05718cd69bd0
> 
> Can see the tendermint/DuplicateVoteEvidence for
> 
> F74DB131709FD55AEA8EC56D22914006802883BB and 71A699F14234B800BACD88EA53867C810A104860
> 
> Thanks for clarifying r.e. the delay. Either way this still needs addressing as without jailing incorrectly configured nodes who are consistently double signing increase the risk of forking right?

Now i see, yeah thats a standard case of double signing on that particular gist we saw two DuplicateVoteEvidence for the same node because the order of the votes, one submitter saw vote A before vote B and for the other submitter vote B was the first one. 

Thankfully tendermint consesus doesn't fork so this is not a big concern. But i personally agree that the penalty for this offense is too light at the moment.

Also this further illustrate the unreliability from our tendermint version of evidence handling to be able to determine and fairly apply the correct penalty, in this case the node would be slashed twice for the same offense , as they are 2 valid evidences about the same offense with the same data as proof (in different order) but submitted from different optics.

**Comment by Andrew-Pohl** [comment] 2022-08-17 17:04
> Thankfully tendermint consesus doesn't fork so this is not a big concern. But i personally agree that the penalty for this offense is too light at the moment.

I think it can fork it's just not designed too and is an attack vector, If a validator node signs multiple versions of a block, it is possible that – with enough misbehaving validators – two versions of the blockchain could exist, each with a ⅔ vote. This is the main reason for jailing on double signing to prevent this attack vector

**Comment by oten91** [comment] 2022-08-17 19:15
> > Thankfully tendermint consesus doesn't fork so this is not a big concern. But i personally agree that the penalty for this offense is too light at the moment.
> 
> I think it can fork it's just not designed too and is an attack vector, If a validator node signs multiple versions of a block, it is possible that – with enough misbehaving validators – two versions of the blockchain could exist, each with a ⅔ vote. This is the main reason for jailing on double signing to prevent this attack vector

@Andrew-Pohl Its a bit more complex than that, Tendermint by design is made to be fork resistant in the sense that it will halt if it detects a fork scenario, avoiding the fork but halting the network. useful blog post to understand scenarios defined by the cosmos team: https://blog.cosmos.network/the-4-classes-of-faults-on-mainnet-bfabfbd2726c 

Keep in mind jailing is not immediate, remember that double signing evidence is collected after the fact, that added to the current issue I described before about evidence handling means that a validator can get punished and jailed for a "weakly filtered" offense it committed N-1000 blocks ago at block N even if its not misbehaving at the moment. 

This item has been in our backlog as we consciously removed the jailing 2.5 years ago and our next consensus breaking change may have some features in line with "solving" this one and other bad behaviours that actually slow our consensus like invalid proposals and missing proposal blocks multiple times.

**Comment by Andrew-Pohl** [comment] 2022-08-17 21:48
> > > Thankfully tendermint consesus doesn't fork so this is not a big concern. But i personally agree that the penalty for this offense is too light at the moment.
> > 
> > 
> > I think it can fork it's just not designed too and is an attack vector, If a validator node signs multiple versions of a block, it is possible that – with enough misbehaving validators – two versions of the blockchain could exist, each with a ⅔ vote. This is the main reason for jailing on double signing to prevent this attack vector
> 
> @Andrew-Pohl Its a bit more complex than that, Tendermint by design is made to be fork resistant in the sense that it will halt if it detects a fork scenario, avoiding the fork but halting the network. useful blog post to understand scenarios defined by the cosmos team: https://blog.cosmos.network/the-4-classes-of-faults-on-mainnet-bfabfbd2726c
> 
> Keep in mind jailing is not immediate, remember that double signing evidence is collected after the fact, that added to the current issue I described before about evidence handling means that a validator can get punished and jailed for a "weakly filtered" offense it committed N-1000 blocks ago at block N even if its not misbehaving at the moment.
> 
> This item has been in our backlog as we consciously removed the jailing 2.5 years ago and our next consensus breaking change may have some features in line with "solving" this one and other bad behaviours that actually slow our consensus like invalid proposals and missing proposal blocks multiple times.

Thanks for the clarification makes sense and great article!

**Closed as completed** 2023-05-05 18:42 UTC
Labels: bug
