### ISSUE TITLE
UnstakeAllMatureValidators, Should continue if not found!

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#885] opened 2020-05-05 18:22 UTC
**Describe the bug**
```
// Unstakes all the unstaking validators that have finished their unstaking period
func (k Keeper) unstakeAllMatureValidators(ctx sdk.Ctx) {
	store := ctx.KVStore(k.storeKey)
	unstakingValidatorsIterator := k.unstakingValidatorsIterator(ctx, ctx.BlockHeader().Time)
	defer unstakingValidatorsIterator.Close()
	for ; unstakingValidatorsIterator.Valid(); unstakingValidatorsIterator.Next() {
		var unstakingVals []sdk.Address
		k.cdc.MustUnmarshalBinaryLengthPrefixed(unstakingValidatorsIterator.Value(), &unstakingVals)
		for _, valAddr := range unstakingVals {
			val, found := k.GetValidator(ctx, valAddr)
			if !found {
				ctx.Logger().Error("validator in the unstaking queue was not found, possible forced unstake?")
			// SHOULD CONTINUE HERE!
}
```

**Comment by oten91** [comment] 2020-05-06 21:41
Duplicate of #886

**Closed as completed** 2020-05-06 21:42 UTC
Labels: bug, high priority
