### ISSUE TITLE
Log level filtering (aka verbosity)?

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#130] opened 2019-01-15 19:45 UTC
https://github.com/Sirupsen/logrus
```go
log.Trace("Something very low level.")
log.Debug("Useful debugging information.")
log.Info("Something noteworthy happened!")
log.Warn("You should probably take a look at this.")
log.Error("Something failed but I'm not quitting.")
// Calls os.Exit(1) after logging
log.Fatal("Bye.")
// Calls panic() after logging
log.Panic("I'm bailing.")
```

**Comment by andrewnguyen22** [comment] 2019-01-22 17:51
Unsure what the issue is here? Could you please provide more details when you get a chance!

**Comment by iajrz** [comment] 2019-01-22 22:10
I mean we should look into verbosity tuning by the time we hit MVP.

**Comment by aqt01** [comment] 2019-10-28 16:39
Thanks! @iajrz  We implemented logrus on this PR 
https://github.com/pokt-network/pocket-core/pull/441

**Comment by aqt01** [comment] 2019-10-28 17:05
Sorry, i misunderstand this issue. 

I created this one 
https://github.com/pokt-network/pocket-core/issues/473

With more description and also referencing this one

**Comment by aqt01** [comment] 2019-11-05 16:16
Closed by 
https://github.com/pokt-network/pocket-core/pull/474

**Closed as completed by aqt01** 2019-11-05 16:16 UTC
Labels: enhancement, documentation, backlog
