### ISSUE TITLE
accounts delete exception

### ISSUE THREAD

**Issue by sl-he** [pokt-network/pocket-core#761] opened 2020-04-09 13:32 UTC
**Describe the bug**
I try to delete account via pocket app

**To Reproduce**
1. Create a new account via _pocket accounts create_
2. Just run _pocket accounts delete_
3. See error

**Expected behavior**
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/pokt-network/pocket-core/app/cmd/cli.glob..func3(0x19e5ee0, 0x1a25dd8, 0x0, 0x0)
        /home/user/source/pocket-core/app/cmd/cli/accounts.go:96 +0x36f
github.com/spf13/cobra.(*Command).execute(0x19e5ee0, 0x1a25dd8, 0x0, 0x0, 0x19e5ee0, 0x1a25dd8)
        /home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x19ed460, 0x4451da, 0x1995680, 0xc000000300)
        /home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/pokt-network/pocket-core/app/cmd/cli.Execute()
        /home/user/source/pocket-core/app/cmd/cli/root.go:41 +0x31
main.main()
        /home/user/source/pocket-core/app/cmd/pocket_core/main.go:8 +0x20

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS (running without GUI, only CLI)
 - Version: RC-0.3.0

**Comment by andrewnguyen22** [comment] 2020-04-09 17:23
This is expected behavior, you cannot delete an account if there are no accounts

I think the solution here is to have a better panic message

**Comment by andrewnguyen22** [comment] 2020-04-09 17:26
This is expected behavior because you passed no arguments. A better panic message should fix this

**Comment by andrewnguyen22** [comment] 2020-04-09 17:28
Closing in favor of #765

**Closed as completed by andrewnguyen22** 2020-04-09 17:28 UTC
