### ISSUE TITLE
Change Challenge burn from proportional to linear

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#722] opened 2020-03-16 14:30 UTC
**Is your feature request related to a problem? Please describe.**
In an amendment to the #704 , the economics team raised a concern on the way the burn to penalize challenges occurs in a manner proportional to the amount staked. 

**Describe the solution you'd like**
Change the burn to use a formula such as follows:

`burnedPOKT = challengeQuantities * (baseChallengeBurn * challengeBurnMultiplier)`

`burnedPOKT = total amount of POKT to be burned in a single Challenge batch`
`challengeQuantities = the amount of challenges being reported on a particular Challenge batch`
`baseChallengeBurn = a network wide param that indicates the base linear amount to be burned for each reported Challenge`
`challengeBurnMultiplier = a network wide param that serves as a multiplier to be used by governance to freely control the amount burned (it will default to 1 in this instance)`

**Additional context**
We want a system that is fair, and because there's no recourse for nodes to dispute the challenges, then it will be up to governance to lower or up the penalty based on the current state of the network.

**Comment by andrewnguyen22** [comment] 2020-03-16 14:51
Seems like too many variables, what's the difference between baseChallengeBurn and challengeBurnMultiplier if both can be changed by governance?
And by proportional I assume you mean proportional to # of relays completed
Proportional is linear btw

**Comment by andrewnguyen22** [comment] 2020-03-16 14:54
What's the expected rate of burn? I figured it would be <5%?
I was even thinking that we may want to go over proportional given what's at stake here. Keep in mind that completing a challenge transaction is a high barrier, one challenge per one relay seems more than fair to me (almost light)

**Comment by mokn** [comment] 2020-03-16 15:01
My concern is that if we burn more strongly than proportional on a relay-per-relay basis it becomes a disincentive for people to become nodes, particularly when it comes to environment variables outside of their control, especially when it comes to syncing blocks.

If there is a transaction that occurs where there is a state change, and there is a node in a Session who did the work honestly by reporting their latest block, but is behind by half a second in time and reports an different number, that node is subject to a challenge request.

We don't want a situation where 2% of my stake gets burned for a series of requests that were outside my control. This will cause total stake from nodes to decline more quickly than what they are earning in POKT.

**Comment by mokn** [comment] 2020-03-16 15:22
After review it looks like the code does enforce a proportional burn on a per relay basis. This is working as intended.

**Comment by andrewnguyen22** [comment] 2020-03-16 15:54
@mokn awesome closing now ^

**Closed as completed by andrewnguyen22** 2020-03-16 15:54 UTC
Labels: enhancement, economics
