### ISSUE TITLE
AllNodes() read is not needed in handle relay

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#842] opened 2020-05-05 09:39 UTC
**Describe the bug**
```
// retrieve all service nodes available from world state to do session generation (the session data is needed to service)
	allNodes := k.GetAllNodes(ctx)
```
Is only used for logging. This is a very expensive call, and it's called again in session.go. Remove here

**Comment by oten91** [comment] 2020-05-06 21:31
duplicate of #826

**Closed as completed by oten91** 2020-05-06 21:31 UTC
Labels: bug, high priority
