### ISSUE TITLE
Intermittant error: code 4 : signature verification failed for the transaction on unjail command

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1081] opened 2020-10-01 16:35 UTC
**Describe the bug**
Submitting an unjail transaction on mainnet results in a Code 4 error approximately 75% of the time.  Repeated attempts eventually result in success.  I have experienced 6 failures in succession.  
The problem does not appear to be related to unconfirmed blocks.  
The behavior has been reported in Discord many times (at least 6).. It is often diagnosed as a fee amount error and "apparently solved" by using a different fee,  but that is not what the real cause is. 

**To Reproduce**

pocket nodes unjail 359ff19da906c934336c38722ab2cfe88c8f727e mainnet 10000 
Enter Password:
http://localhost:8082/v1/client/rawtx
{
    "code": 4,
    "height": "0",
    "raw_log": "{\"codespace\":\"sdk\",\"code\":4,\"message\":\"signature verification failed for the transaction\"}",
    "txhash": "342C30EC53DA941B7CAE180B7F55CA49E8895639F9432A90D9430956758F80EF"
}

**Expected behavior**
pocket nodes unjail 359ff19da906c934336c38722ab2cfe88c8f727e mainnet 100000
Enter Password:
http://localhost:8082/v1/client/rawtx

    "raw_log": "[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]",
    "txhash": "E3E0BEF441D50DEF642A77DD2F4208EF5B0791F809D52BC4D8A2704E534D3FA0"

**Comment by andrewnguyen22** [comment] 2020-10-05 15:43
# Formal Bug Investigation Report

**Unable to reproduce on a single node instance with 20+ attempts.** 

I have been granted 100 POKT from PNI to test on mainnet.

# NOTES:
**ADDRESS USED**

354f5db6cd6f61ea9b27e90fa585efc06ef517d3

**START HEIGHT**

6559

**COMMAND USED**

pocket nodes unjail 354f5db6cd6f61ea9b27e90fa585efc06ef517d3 mainnet 10000

**THE NODE PERFORMING THE UNJAIL IS NOT A VALIDATOR NOR IS JAILED**

 - This is acceptable due to the error at hand being in the ante handler (just confirming the signature and not doing any state. validation)
- Infact, these transactions will always be invalid, but this error happens immediately upon returning the result of the transaction (even before played against the state)

**DUE TO THE ABOVE, THESE TX SHOULD FAIL WITH**: 

`that address is not associated with any known validator`

# RESULTS:
## ATTEMPT 1
#### TXHASH
D0C552CCB0D0CB2FEFB0618A568B50D9DA64F4F48871CEC52EAEB9E819E5EB42
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 2
#### TXHASH
79461227E6827801D36239B826A1AD89CC9A2EA6CDE333922F68B35F062A9B53
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 3
#### TXHASH
8013D6B99A7B6DEB4527E2F06CBE799FC7657AC3544D1B4541B90444696FE294
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]"
## ATTEMPT 4
#### TXHASH
E0918601B332BCD548D8C0FDA2F51394DE57C30A8188F7A776E2115088D93024
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 5
#### TXHASH
D700EDA4815D32FFF88EEC7966E6BAC08A2C7A5DCC193A5FFD02BFA125899F1D
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 6
#### TXHASH
9965E85B8E32954F015118715A70A6B5D842EDC7871E93EBF090120D4610F4DE
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 7
#### TXHASH
B83FEFCBEC4D574EFD150DBB34C1BEF7A78466EA8A4DCAE1AC043B26E0C5D515
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 8
#### TXHASH
553F8B95A33A808F2F07B09803A82766C46DFED1A9BF73064A1A3C560A9835FE
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 9
#### TXHASH
B675FE900F1CE6BF3BBD58CF560DFF3FC685DBA69BA04876C2BCD53190DBD994
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 10
#### TXHASH
367B5747892C4F999869AE614C13581932E3F99A33EFCFD09EC3EFB2A69FE43C
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 11
#### TXHASH
A0BAAAE5A6F507AE466A4A7A4CE2C185C84DC20D1E87AEF4CA04115C911253DB
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 12
#### TXHASH
3CD815388C57B3CB1FC3FB131F537D50E1092FE2D6D1687BDD2C9EDFEA25BA39
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 13
#### TXHASH
C04115D5E087CBBEDB43EA2F88CBA180FC8AD2AC53E591BE24802127F5633EBF
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 14
#### TXHASH
1CF00317653D23061558E343AEA8FF2CBB118FE4FC1A4AFC8830FE39954089AF
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`
## ATTEMPT 15
#### TXHASH
4E8001EC872852529181DFF1992F471670CA95199A7434F66DDE9A4BE5CF3FA7
#### Initial Result
`[{\"msg_index\":0,\"success\":true,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"unjail_validator\"}]}]}]`

After running 15 consecutive successful unjail transactions. I am closing this issue unless more evidence is added on this front.

The most common reason for invalid signature error:
- Wrong fee (`10000` is the correct fee)
- Wrong chainID (`mainnet`)
- Wrong key setup node_key.json priv_val_key.json does not match unjail address

EDIT: One last note from initial investigation -> pocket query tx 342C30EC53DA941B7CAE180B7F55CA49E8895639F9432A90D9430956758F80EF
returns null transaction... This was the transaction from the original report

**Closed as completed by andrewnguyen22** 2020-10-05 15:43 UTC

**Comment by andrewnguyen22** [comment] 2021-01-06 17:12
Comment from the original poster @BenVanGithub: 
```
I only experience it now if I forget to wait one block after a set-validator or a pocket start.
```
See [FAQ](https://github.com/pokt-network/pocket-core/issues/1172)
